#!/usr/bin/env python3
ansFile = open("./BoolAnswerOutput")
ansLine = ansFile.readlines()


import tkinter as tk
from tkinter import ttk

# Creating tkinter window
window = tk.Tk()
window.title('Combobox')
window.geometry('500x250')

# label text for title
ttk.Label(window, text="GFG Combobox Widget",
          background='green', foreground="white",
          font=("Times New Roman", 15)).grid(row=0, column=1)

# label
ttk.Label(window, text="Select the expression:",
          font=("Times New Roman", 10)).grid(column=0,
                                             row=5, padx=10, pady=25)

# Combobox creation
n = tk.StringVar()
expression = ttk.Combobox(window, width=27, textvariable=n)

# Adding combobox drop down list
expressions = ansFile.readlines()

monthchoosen.grid(column=1, row=5)
monthchoosen.current()
window.mainloop()